version: '3'

services:
  app:
    image: blbraner/fastapi_test_db:latest
    ports:
      - "8081:8081"
    volumes:
      - ./app:/opt/service/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8081  --reload
  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=torqata
    ports:
      - 5432:5432
