name: ci
on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: blbraner
          password: c6941ad1-7c86-4d71-91b1-73ce9ca8ca94
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  blbraner/fastapi_test_db:latest

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container: blbraner/fastapi_test_db:latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Pytest
        run: poetry run pytest